//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTNster.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BTNsterEntities : DbContext
    {
        public BTNsterEntities()
            : base("name=BTNsterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BTNRelease> BTNRelease { get; set; }
        public virtual DbSet<Filter> Filter { get; set; }
        public virtual DbSet<FilterSeries> FilterSeries { get; set; }
        public virtual DbSet<Release> Release { get; set; }
    }
}
