//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTNster.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilterSeries
    {
        public long FilterID { get; set; }
        public long FilterSeriesID { get; set; }
        public string SeriesName { get; set; }
        public string SeriesTitle { get; set; }
        public Nullable<long> SeasonNumber { get; set; }
        public Nullable<long> EpisodeNumber { get; set; }
    
        public virtual Filter Filter { get; set; }
    }
}
