//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTNster.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Filter()
        {
            this.FilterSeries = new HashSet<FilterSeries>();
        }
    
        public long FilterID { get; set; }
        public string FilterTitle { get; set; }
        public string Containers { get; set; }
        public string Sources { get; set; }
        public string Resolutions { get; set; }
        public string Codecs { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> RememberHistory { get; set; }
        public Nullable<bool> DownloadBetterReleases { get; set; }
        public Nullable<bool> SceneYes { get; set; }
        public Nullable<bool> SceneNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FilterSeries> FilterSeries { get; set; }
    }
}
