//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTNster.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Release
    {
        public long ReleaseID { get; set; }
        public string RawIRCAnnounce { get; set; }
        public string RawIRCAnnounceDate { get; set; }
    }
}
